name: holiday_itinerary
version: "1.0.0"
config-version: 2

profile: holiday_itinerary

model-paths:
  - models

target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  holiday_itinerary:
    staging:
      +materialized: view
    marts:
      +materialized: table
