# --- API CONFIGURATION ---
api:
  # The specific DATAtourisme feed URL
  feed_url: "https://diffuseur.datatourisme.fr/webservice/"
  
  # ETL Logic settings
  batch_size: 1000
  bronze_table: "raw_api_data"
  silver_table: "normalized_pois"
  gold_table: "processed_pois"

# --- STORAGE PATHS ---
paths:
  # These paths are relative to the /app folder inside Docker
  raw_data_dir: "data/raw"
  output_file: "datatourisme_cache.json"