FROM apache/airflow:2.10.4-python3.12

USER root
RUN apt-get update && apt-get install -y \
    gcc \
    default-jre-headless \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

USER airflow
COPY requirements.txt /tmp/requirements.txt
COPY requirements-analytics.txt /tmp/requirements-analytics.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt -r /tmp/requirements-analytics.txt

COPY --chown=airflow:root airflow/dags /opt/airflow/dags
COPY --chown=airflow:root dbt /opt/holiday/dbt
COPY --chown=airflow:root src /opt/holiday/src
COPY --chown=airflow:root config.yaml /opt/holiday/config.yaml
