"""FastAPI service for exploring generated holiday itinerary data."""

from __future__ import annotations

import os
import sys
from contextlib import closing
from datetime import datetime, timedelta
from math import asin, cos, radians, sin, sqrt
from typing import Any

import pandas as pd
import requests
from fastapi import FastAPI, HTTPException, Query, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from prometheus_client import CONTENT_TYPE_LATEST, Counter, Gauge, Histogram, generate_latest
from sklearn.cluster import KMeans

CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.dirname(CURRENT_DIR)
PROJECT_ROOT = os.path.dirname(SRC_DIR)
for path in (PROJECT_ROOT, SRC_DIR):
    if path not in sys.path:
        sys.path.append(path)

try:
    from src.utils.connections import conn_env, neo4j_env
    from src.streaming.kafka_events import publish_event
except ImportError:
    from utils.connections import conn_env, neo4j_env
    from streaming.kafka_events import publish_event


app = FastAPI(title="Holiday Itinerary API", version="1.0.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

HTTP_REQUESTS_TOTAL = Counter(
    "holiday_api_http_requests_total",
    "Total HTTP requests handled by the API.",
    ["method", "path", "status_code"],
)
HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "holiday_api_http_request_duration_seconds",
    "HTTP request latency by method and path.",
    ["method", "path"],
)
ITINERARIES_GENERATED_TOTAL = Counter(
    "holiday_itineraries_generated_total",
    "Itineraries generated by city.",
    ["city"],
)
ITINERARY_PLACES_SELECTED_TOTAL = Counter(
    "holiday_itinerary_places_selected_total",
    "Places selected into generated itineraries.",
    ["city"],
)
WEATHER_REQUESTS_TOTAL = Counter(
    "holiday_weather_requests_total",
    "Current weather requests by city.",
    ["city", "status"],
)
KAFKA_EVENTS_TOTAL = Counter(
    "holiday_kafka_events_total",
    "Kafka publish attempts by topic and status.",
    ["topic", "status"],
)
ITINERARY_CATEGORY_MATCH_RATE = Gauge(
    "holiday_itinerary_category_match_rate",
    "Share of selected itinerary places matching at least one requested category.",
    ["city"],
)
ITINERARY_AVG_DISTANCE_KM = Gauge(
    "holiday_itinerary_avg_distance_km",
    "Average distance in kilometers between consecutive itinerary stops.",
    ["city"],
)
ITINERARY_AVG_RECOMMENDATIONS = Gauge(
    "holiday_itinerary_avg_recommendations",
    "Average graph recommendation count per selected itinerary place.",
    ["city"],
)
ITINERARY_WEATHER_SUITABILITY_SCORE = Gauge(
    "holiday_itinerary_weather_suitability_score",
    "Weather suitability score for selected itinerary mix from 0 to 1.",
    ["city"],
)


@app.middleware("http")
async def record_http_metrics(request: Request, call_next):
    path = request.url.path
    with HTTP_REQUEST_DURATION_SECONDS.labels(request.method, path).time():
        response = await call_next(request)
    HTTP_REQUESTS_TOTAL.labels(request.method, path, str(response.status_code)).inc()
    return response


def _publish_platform_event(
    topic: str, event_type: str, payload: dict[str, Any], key: str | None = None
) -> None:
    try:
        publish_event(topic, event_type, payload, key=key)
        KAFKA_EVENTS_TOTAL.labels(topic, "published").inc()
    except Exception:
        # Kafka is a mandatory platform service, but request handling should remain
        # resilient while a broker is restarting. The failure is visible in metrics.
        KAFKA_EVENTS_TOTAL.labels(topic, "failed").inc()


class ItineraryRequest(BaseModel):
    city: str = Field(..., min_length=1)
    days: int = Field(default=3, ge=1, le=50)
    max_places_per_day: int = Field(default=5, ge=1, le=50)
    categories: list[str] = Field(default_factory=list)


class PlannedPlace(BaseModel):
    id: str
    name: str
    city: str | None = None
    category: str = "Tourism"
    categories: list[str] = Field(default_factory=list)
    lat: float
    lon: float
    address: str | None = None
    description: str | None = None
    website: str | None = None
    start_time: str
    end_time: str
    recommendations: list[str] = Field(default_factory=list)


class DayPlan(BaseModel):
    day: int
    places: list[PlannedPlace]


class CitySummary(BaseModel):
    city: str
    poi_count: int


class AppSummary(BaseModel):
    places: int
    cities: int
    popular_destinations: int
    categories: int
    clusters: int


class CurrentWeather(BaseModel):
    city: str
    lat: float
    lon: float
    observed_at: str | None = None
    temperature_2m: float | None = None
    relative_humidity_2m: float | None = None
    precipitation: float | None = None
    rain: float | None = None
    weather_code: int | None = None
    wind_speed_10m: float | None = None
    wind_direction_10m: float | None = None
    source: str


def _query_dataframe(conn, query: str, params: tuple[Any, ...] = ()) -> pd.DataFrame:
    with conn.cursor() as cursor:
        cursor.execute(query, params)
        rows = cursor.fetchall()
        columns = [desc[0] for desc in cursor.description]
    return pd.DataFrame(rows, columns=columns)


def _json_records(df: pd.DataFrame) -> list[dict[str, Any]]:
    if df.empty:
        return []
    # Pandas represents missing values as NaN/NaT, but strict JSON does not allow
    # NaN floats. Convert every dataframe missing value to Python None.
    clean_df = df.astype(object).where(pd.notna(df), None)
    return clean_df.to_dict(orient="records")


def _json_value(value):
    return None if pd.isna(value) else value


def _database_ready(conn) -> bool:
    with conn.cursor() as cursor:
        cursor.execute("SELECT to_regclass('public.silver_places')")
        return cursor.fetchone()[0] is not None


def _places_query(where_clause: str = "", limit_clause: str = ""):
    return f"""
        WITH filtered_places AS (
            SELECT
                p.id,
                p.name,
                p.city,
                p.lat,
                p.lon,
                p.address,
                p.description,
                p.website
            FROM silver_places p
            {where_clause}
            ORDER BY p.name
            {limit_clause}
        )
        SELECT
            p.id,
            p.name,
            p.city,
            p.lat,
            p.lon,
            p.address,
            p.description,
            p.website,
            COALESCE(
                ARRAY_AGG(DISTINCT c.name) FILTER (WHERE c.name IS NOT NULL),
                ARRAY[]::TEXT[]
            ) AS categories
        FROM filtered_places p
        LEFT JOIN silver_place_categories pc ON p.id = pc.place_id
        LEFT JOIN silver_categories c ON pc.category_id = c.id
        GROUP BY p.id, p.name, p.city, p.lat, p.lon, p.address, p.description, p.website
        ORDER BY p.name
    """


def _load_places_for_city(conn, city: str, limit: int) -> pd.DataFrame:
    query = _places_query(
        where_clause="WHERE LOWER(p.city) = LOWER(%s)",
        limit_clause="LIMIT %s",
    )
    return _query_dataframe(conn, query, (city, limit))


def _load_city_centroid(conn, city: str) -> tuple[float, float] | None:
    with conn.cursor() as cursor:
        cursor.execute(
            """
            SELECT AVG(lat)::float AS lat, AVG(lon)::float AS lon
            FROM silver_places
            WHERE LOWER(city) = LOWER(%s)
              AND lat IS NOT NULL
              AND lon IS NOT NULL
            """,
            (city,),
        )
        row = cursor.fetchone()
    if not row or row[0] is None or row[1] is None:
        return None
    return float(row[0]), float(row[1])


def _fetch_current_weather(lat: float, lon: float) -> dict[str, Any]:
    response = requests.get(
        "https://api.open-meteo.com/v1/forecast",
        params={
            "latitude": lat,
            "longitude": lon,
            "current": ",".join(
                [
                    "temperature_2m",
                    "relative_humidity_2m",
                    "precipitation",
                    "rain",
                    "weather_code",
                    "wind_speed_10m",
                    "wind_direction_10m",
                ]
            ),
            "timezone": "auto",
        },
        timeout=10,
    )
    response.raise_for_status()
    payload = response.json()
    return payload.get("current") or {}


def _get_recommendations_for_places(
    place_ids: list[str], city: str | None, limit: int = 3
) -> dict[str, list[str]]:
    if not place_ids:
        return {}
    try:
        from neo4j import GraphDatabase, Query

        uri, auth = neo4j_env()
        driver = GraphDatabase.driver(uri, auth=auth, connection_timeout=2)
        try:
            with driver.session() as session:
                result = session.run(
                    Query(
                        """
                    UNWIND $place_ids AS place_id
                    MATCH (p:POI {id: place_id})-[:HAS_CATEGORY]->(:Category)<-[:HAS_CATEGORY]-(similar:POI)
                    OPTIONAL MATCH (similar)-[:LOCATED_IN]->(city:City)
                    WHERE similar.id <> place_id
                      AND ($city IS NULL OR toLower(city.name) = toLower($city))
                      AND similar.label IS NOT NULL
                    WITH place_id, similar.label AS name
                    ORDER BY name
                    WITH place_id, collect(DISTINCT name)[0..$limit] AS recommendations
                    RETURN place_id, recommendations
                    """,
                        timeout=3,
                    ),
                    place_ids=place_ids,
                    city=city,
                    limit=limit,
                )
                return {
                    record["place_id"]: list(record["recommendations"] or [])
                    for record in result
                }
        finally:
            driver.close()
    except Exception:
        return {}


def _row_categories(row) -> list[str]:
    categories = row.get("categories") or []
    return list(categories) if isinstance(categories, (list, tuple)) else []


def _normalize_categories(categories: list[str] | None) -> list[str]:
    if not categories:
        return []
    normalized = []
    seen = set()
    for category in categories:
        cleaned = category.strip()
        key = cleaned.lower()
        if not cleaned or key in seen:
            continue
        normalized.append(cleaned)
        seen.add(key)
    return normalized


def _category_match_count(
    row_categories: list[str], preferred_categories: list[str]
) -> int:
    preferred = {category.lower() for category in preferred_categories}
    return sum(1 for category in row_categories if category.lower() in preferred)


def _haversine_km(lat_a: float, lon_a: float, lat_b: float, lon_b: float) -> float:
    earth_radius_km = 6371.0
    delta_lat = radians(lat_b - lat_a)
    delta_lon = radians(lon_b - lon_a)
    start_lat = radians(lat_a)
    end_lat = radians(lat_b)
    value = (
        sin(delta_lat / 2) ** 2
        + cos(start_lat) * cos(end_lat) * sin(delta_lon / 2) ** 2
    )
    return 2 * earth_radius_km * asin(sqrt(value))


def _average_stop_distance_km(itinerary: list[DayPlan]) -> float:
    distances = []
    for day in itinerary:
        for previous, current in zip(day.places, day.places[1:]):
            distances.append(
                _haversine_km(previous.lat, previous.lon, current.lat, current.lon)
            )
    if not distances:
        return 0.0
    return sum(distances) / len(distances)


def _category_match_rate(
    itinerary: list[DayPlan], preferred_categories: list[str]
) -> float:
    selected_places = [place for day in itinerary for place in day.places]
    if not selected_places:
        return 0.0
    if not preferred_categories:
        return 1.0
    preferred = {category.lower() for category in preferred_categories}
    matched = sum(
        1
        for place in selected_places
        if any(category.lower() in preferred for category in place.categories)
    )
    return matched / len(selected_places)


def _average_recommendation_count(itinerary: list[DayPlan]) -> float:
    selected_places = [place for day in itinerary for place in day.places]
    if not selected_places:
        return 0.0
    return sum(len(place.recommendations) for place in selected_places) / len(
        selected_places
    )


def _is_outdoor_place(place: PlannedPlace) -> bool:
    outdoor_terms = {
        "beach",
        "garden",
        "hiking",
        "lake",
        "natural",
        "nature",
        "outdoor",
        "park",
        "trail",
        "viewpoint",
        "walk",
    }
    category_text = " ".join(place.categories + [place.category]).lower()
    return any(term in category_text for term in outdoor_terms)


def _weather_suitability_score(
    itinerary: list[DayPlan], weather: dict[str, Any] | None
) -> float:
    selected_places = [place for day in itinerary for place in day.places]
    if not selected_places or not weather:
        return 1.0

    outdoor_ratio = sum(1 for place in selected_places if _is_outdoor_place(place)) / len(
        selected_places
    )
    precipitation = float(weather.get("precipitation") or 0)
    rain = float(weather.get("rain") or 0)
    wind_speed = float(weather.get("wind_speed_10m") or 0)
    weather_code = int(weather.get("weather_code") or 0)
    bad_weather = precipitation > 0 or rain > 0 or weather_code >= 51 or wind_speed >= 40
    if not bad_weather:
        return 1.0
    return max(0.0, 1.0 - outdoor_ratio)


def _load_weather_for_itinerary(city: str) -> dict[str, Any] | None:
    try:
        with closing(conn_env()) as conn:
            centroid = _load_city_centroid(conn, city)
        if centroid is None:
            return None
        return _fetch_current_weather(*centroid)
    except Exception:
        return None


def _select_day_rows(
    day_rows: pd.DataFrame, preferred_categories: list[str], max_places: int
) -> list[dict[str, Any]]:
    sorted_rows = day_rows.sort_values(["distance_to_day_center", "name"])
    if not preferred_categories:
        return sorted_rows.head(max_places).to_dict(orient="records")

    return sorted_rows[sorted_rows["category_match_count"] > 0].head(
        max_places
    ).to_dict(orient="records")


def _record_itinerary_quality_metrics(
    city: str,
    itinerary: list[DayPlan],
    preferred_categories: list[str],
    weather: dict[str, Any] | None,
) -> dict[str, float]:
    metrics = {
        "category_match_rate": _category_match_rate(itinerary, preferred_categories),
        "avg_distance_km": _average_stop_distance_km(itinerary),
        "avg_recommendations": _average_recommendation_count(itinerary),
        "weather_suitability_score": _weather_suitability_score(itinerary, weather),
    }
    ITINERARY_CATEGORY_MATCH_RATE.labels(city).set(metrics["category_match_rate"])
    ITINERARY_AVG_DISTANCE_KM.labels(city).set(metrics["avg_distance_km"])
    ITINERARY_AVG_RECOMMENDATIONS.labels(city).set(metrics["avg_recommendations"])
    ITINERARY_WEATHER_SUITABILITY_SCORE.labels(city).set(
        metrics["weather_suitability_score"]
    )
    return metrics


@app.get("/health")
def health():
    with closing(conn_env()) as conn:
        return {"status": "ok", "database_ready": _database_ready(conn)}


@app.get("/metrics")
def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.get("/summary", response_model=AppSummary)
def summary():
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        with conn.cursor() as cursor:
            cursor.execute("""
                WITH destination_counts AS (
                    SELECT city, COUNT(*) AS poi_count
                    FROM silver_places
                    WHERE city IS NOT NULL AND BTRIM(city) <> ''
                    GROUP BY city
                )
                SELECT
                    (SELECT COUNT(*) FROM silver_places) AS places,
                    (SELECT COUNT(*) FROM destination_counts) AS cities,
                    (SELECT COUNT(*) FROM destination_counts WHERE poi_count >= 10) AS popular_destinations,
                    (SELECT COUNT(*) FROM silver_categories) AS categories
                """)
            places, cities, popular_destinations, categories = cursor.fetchone()
            cursor.execute("SELECT to_regclass('public.gold_clusters')")
            if cursor.fetchone()[0] is None:
                clusters = 0
            else:
                cursor.execute("SELECT COUNT(*) FROM gold_clusters")
                clusters = cursor.fetchone()[0]
    return AppSummary(
        places=places,
        cities=cities,
        popular_destinations=popular_destinations,
        categories=categories,
        clusters=clusters,
    )


@app.get("/cities", response_model=list[CitySummary])
def cities(limit: int = Query(default=25, ge=1, le=200)):
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        df = _query_dataframe(
            conn,
            """
            SELECT city, COUNT(*) AS poi_count
            FROM silver_places
            WHERE city IS NOT NULL AND city <> ''
            GROUP BY city
            ORDER BY poi_count DESC, city
            LIMIT %s
            """,
            (limit,),
        )
    return [
        CitySummary(city=row.city, poi_count=row.poi_count) for row in df.itertuples()
    ]


@app.get("/categories", response_model=list[str])
def categories(
    city: str | None = None,
    limit: int = Query(default=100, ge=1, le=500),
):
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        if city:
            df = _query_dataframe(
                conn,
                """
                SELECT c.name
                FROM silver_places p
                JOIN silver_place_categories pc ON pc.place_id = p.id
                JOIN silver_categories c ON c.id = pc.category_id
                WHERE LOWER(p.city) = LOWER(%s)
                GROUP BY c.name
                ORDER BY COUNT(*) DESC, c.name
                LIMIT %s
                """,
                (city, limit),
            )
            return df["name"].tolist()

        df = _query_dataframe(
            conn,
            "SELECT name FROM silver_categories ORDER BY name LIMIT %s",
            (limit,),
        )
    return df["name"].tolist()


@app.get("/places")
def places(
    city: str | None = None,
    category: str | None = None,
    categories: list[str] | None = Query(default=None),
    limit: int = Query(default=100, ge=1, le=500),
):
    filters = []
    params: list[Any] = []
    if city:
        filters.append("LOWER(p.city) = LOWER(%s)")
        params.append(city)
    selected_categories = _normalize_categories([category] if category else categories)
    if selected_categories:
        filters.append("""
            EXISTS (
                SELECT 1
                FROM silver_place_categories pc_filter
                JOIN silver_categories c_filter ON pc_filter.category_id = c_filter.id
                WHERE pc_filter.place_id = p.id
                  AND LOWER(c_filter.name) = ANY(%s)
            )
            """)
        params.append([category.lower() for category in selected_categories])

    where_clause = f"WHERE {' AND '.join(filters)}" if filters else ""
    params.append(limit)
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        df = _query_dataframe(
            conn,
            _places_query(
                where_clause=where_clause,
                limit_clause="LIMIT %s",
            ),
            tuple(params),
        )
    return _json_records(df)


@app.get("/weather/current", response_model=CurrentWeather)
def current_weather(city: str = Query(..., min_length=1)):
    requested_city = city.strip()
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        centroid = _load_city_centroid(conn, requested_city)

    if centroid is None:
        raise HTTPException(
            status_code=404, detail=f"City '{requested_city}' was not found."
        )

    lat, lon = centroid
    try:
        current = _fetch_current_weather(lat, lon)
    except requests.RequestException as exc:
        WEATHER_REQUESTS_TOTAL.labels(requested_city, "failed").inc()
        raise HTTPException(
            status_code=502, detail=f"Weather provider request failed: {exc}"
        ) from exc

    WEATHER_REQUESTS_TOTAL.labels(requested_city, "ok").inc()
    _publish_platform_event(
        "weather_snapshots",
        "weather.current_requested",
        {
            "city": requested_city,
            "lat": round(lat, 6),
            "lon": round(lon, 6),
            "weather": current,
        },
        key=requested_city.lower(),
    )
    return CurrentWeather(
        city=requested_city,
        lat=round(lat, 6),
        lon=round(lon, 6),
        observed_at=current.get("time"),
        temperature_2m=current.get("temperature_2m"),
        relative_humidity_2m=current.get("relative_humidity_2m"),
        precipitation=current.get("precipitation"),
        rain=current.get("rain"),
        weather_code=current.get("weather_code"),
        wind_speed_10m=current.get("wind_speed_10m"),
        wind_direction_10m=current.get("wind_direction_10m"),
        source="Open-Meteo Forecast API",
    )


@app.post("/generate-itinerary", response_model=list[DayPlan])
def generate_itinerary(request: ItineraryRequest):
    preferred_categories = _normalize_categories(request.categories)
    with closing(conn_env()) as conn:
        if not _database_ready(conn):
            raise HTTPException(
                status_code=503, detail="silver_places is not loaded yet."
            )
        df = _load_places_for_city(
            conn,
            request.city.strip(),
            min(max(request.days * request.max_places_per_day * 50, 500), 2000),
        )

    if df.empty:
        raise HTTPException(
            status_code=404, detail=f"City '{request.city}' was not found."
        )

    cluster_count = min(request.days, len(df))
    if cluster_count > 1:
        coords = df[["lat", "lon"]].astype(float).values
        kmeans = KMeans(
            n_clusters=cluster_count,
            random_state=42,
            n_init=10,
        )
        df["day_assignment"] = kmeans.fit_predict(coords)
        df["distance_to_day_center"] = [
            ((lat - kmeans.cluster_centers_[label][0]) ** 2)
            + ((lon - kmeans.cluster_centers_[label][1]) ** 2)
            for (lat, lon), label in zip(coords, df["day_assignment"])
        ]
    else:
        df["day_assignment"] = 0
        df["distance_to_day_center"] = 0
    df["category_match_count"] = df["categories"].map(
        lambda categories: _category_match_count(
            list(categories or []), preferred_categories
        )
    )
    if preferred_categories:
        df = df[df["category_match_count"] > 0].copy()
        if df.empty:
            raise HTTPException(
                status_code=404,
                detail=(
                    "No places in this city match the selected interests: "
                    f"{', '.join(preferred_categories)}."
                ),
            )

    selected_rows_by_day = []
    for day_index in range(cluster_count):
        selected_rows_by_day.append(
            (
                day_index,
                _select_day_rows(
                    df[df["day_assignment"] == day_index],
                    preferred_categories,
                    request.max_places_per_day,
                ),
            )
        )

    selected_place_ids = [
        row["id"] for _, rows in selected_rows_by_day for row in rows if row.get("id")
    ]
    recommendation_map = _get_recommendations_for_places(
        selected_place_ids, request.city.strip()
    )

    itinerary: list[DayPlan] = []
    for day_index, rows in selected_rows_by_day:
        current_time = datetime.strptime("09:00", "%H:%M")
        planned_places = []

        for row in rows:
            end_time = current_time + timedelta(hours=2)
            categories = _row_categories(row)
            planned_places.append(
                PlannedPlace(
                    id=row["id"],
                    name=row["name"],
                    city=row.get("city"),
                    category=categories[0] if categories else "Tourism",
                    categories=categories,
                    lat=row["lat"],
                    lon=row["lon"],
                    address=_json_value(row.get("address")),
                    description=_json_value(row.get("description")),
                    website=_json_value(row.get("website")),
                    start_time=current_time.strftime("%H:%M"),
                    end_time=end_time.strftime("%H:%M"),
                    recommendations=recommendation_map.get(row["id"], []),
                )
            )
            current_time = end_time + timedelta(minutes=30)

        itinerary.append(DayPlan(day=day_index + 1, places=planned_places))

    selected_count = sum(len(day.places) for day in itinerary)
    requested_city = request.city.strip()
    weather_for_metrics = _load_weather_for_itinerary(requested_city)
    quality_metrics = _record_itinerary_quality_metrics(
        requested_city,
        itinerary,
        preferred_categories,
        weather_for_metrics,
    )
    ITINERARIES_GENERATED_TOTAL.labels(requested_city).inc()
    ITINERARY_PLACES_SELECTED_TOTAL.labels(requested_city).inc(selected_count)
    _publish_platform_event(
        "itinerary_requests",
        "itinerary.generated",
        {
            "city": requested_city,
            "days": request.days,
            "max_places_per_day": request.max_places_per_day,
            "categories": preferred_categories,
            "selected_place_count": selected_count,
            "quality_metrics": quality_metrics,
        },
        key=requested_city.lower(),
    )
    return itinerary


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
